### ISSUE TITLE
Appears broken on MediaWiki >= 1.42

### ISSUE THREAD

**Issue by clarfonthey** [Joeytje50/JWB#20]
Poking through the debugger, it appears to fail on this like:

```js
JWB.page = response.query.pages[response.query.pageids[0]];
```

Since the page it's being queried is a redirect, it appears to only offer a `redirects` key instead of a `pages` key. I'm not sure why or how the API changed here, but this does seem like a legitimate bug.

Ran into this since Miraheze recently updated to 1.42, and JWB no longer works on there for me.

**Comment by Joeytje50** [comment]
Hmmm this sounds like it may indeed be an annoying bug, but I can't find any information about the `pages` key being dropped. On the API:Query page (https://www.mediawiki.org/wiki/API:Query#Resolving_redirects) the first example shows a response that contains both a `redirects` and `pages` key.

Could you please provide me a concrete example of how I could reproduce this bug? I assume I'd have to look up a page that is a redirect to some other page, but would I need to set the 'Redirects:' option to 'Follow' or 'Edit'? And what is the behaviour when doing this? Will JWB just break, or will it still work somewhat in a broken state?

**Comment by clarfonthey** [comment]
I'll get back to you on an example; at least for me, it happened simply by having a redirect in the page list, but for all I know it was a quirk of the particular setup Miraheze was using that has since been fixed.

**Comment by clarfonthey** [comment]
Yeah, it seems to be working now. I'm just going to close this as unreproducible.
