### ISSUE TITLE
Stopped working after latest updates

### ISSUE THREAD

**Issue by stjohann** [Joeytje50/JWB#22]
Hey. Thank you so much for this script, I run a lot of bot edits from it.

It seems to have stopped working in Russian Wikipedia after the latest updates. Saving any edits is now impossible, and the links to pages now link to incorrect locations:
`https://ru.wikipedia.org/wiki/Википедия:AutoWikiBrowser/Приимковы-Ростовские`

![image](https://github.com/user-attachments/assets/84dc5597-b281-452f-bd91-092b9b9db11c)

The URL seems to be correct when using `?uselang=en`. Saving still fails.

**Comment by Eejit43** [comment]
@Joeytje50 This has nothing to do with the language, the script has broken on all wikis as of the latest PR.

**Comment by Joeytje50** [comment]
I've deployed some fixes for the issues that were reported. If you are still having problems with russian JWB, please update. Otherwise, I'll close this issue assuming it was fixed along with the fixes to the english version.

**Comment by stjohann** [comment]
Seems to be working fine now, thanks!

**Comment by Eejit43** [comment]
Working perfectly now, thank you very much!!
