### ISSUE TITLE
Bad position of the checkboxes after the summary form

### ISSUE THREAD

**Issue by lens0021** [Joeytje50/JWB#9]
My browser renders the checkboxes and the summary form in the same position:
![image](https://user-images.githubusercontent.com/28209361/128281734-fde3c6a1-d26c-440b-a4a7-8b5b86102761.png)

## Expected behavior
![image](https://user-images.githubusercontent.com/28209361/128281838-deb8db71-a704-4f05-ab8c-a8db9b7f73c4.png)

maybe. the screenshot is from https://commons.wikimedia.org?oldid=510552777

## Environments
I have run JWB on [a Fandom wiki](https://mabinogi.fandom.com/) by execute `mw.loader.load('//en.wikipedia.org/w/index.php?title=User:Joeytje50/JWB.js/load.js&action=raw&ctype=text/javascript');`.

* os: Ubuntu 21.04
* user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36

**Comment by chrishanel** [comment]
Also experiencing this issue in Chrome on MacOS.

**Comment by Joeytje50** [comment]
I hope the commit I just added fixes this issue for your browsers. I was not able to reproduce this, but based on the screenshots this fix should solve the issue. If not, please let me know!

**Comment by lens0021** [comment]
Fixed! Thank you.
